export enum OtaVariableEnum {
  CONFISCATION = 'CONFISCATION',
  AREA = 'AREA',
  CADASTRAL_REGISTRATION_STATUS = 'CADASTRAL_REGISTRATION_STATUS',
  MORTGAGES = 'MORTGAGES',
  OWNERS = 'OWNERS',
  PROPERTIES = 'PROPERTIES',
  PROPERTY_DEALING = 'PROPERTY_DEALING',
}
